import { type LucideProps } from 'lucide-react'
import {
  // ── Rooms: core living ──
  Bed,
  BedDouble,
  BedSingle,
  Sofa,
  Armchair,
  Tv,
  TvMinimal,
  CookingPot,
  UtensilsCrossed,
  ForkKnife,
  ChefHat,
  Refrigerator,
  Microwave,
  Bath,
  ShowerHead,
  Toilet,
  TowelRack,
  SoapDispenserDroplet,
  MirrorRound,
  // ── Rooms: circulation & utility ──
  DoorOpen,
  DoorClosed,
  Footprints,
  WashingMachine,
  Shirt,
  SprayCan,
  Archive,
  Box,
  Key,
  Backpack,
  AirVent,
  // ── Rooms: work & study ──
  Briefcase,
  Monitor,
  Laptop,
  BookOpen,
  Library,
  LampDesk,
  Printer,
  PenTool,
  // ── Rooms: hobbies & entertainment ──
  Gamepad2,
  Puzzle,
  Dices,
  Blocks,
  Palette,
  Paintbrush,
  Scissors,
  Spool,
  Ruler,
  PencilRuler,
  Piano,
  Guitar,
  Drum,
  Music,
  Mic,
  AudioLines,
  Clapperboard,
  Film,
  Projector,
  Popcorn,
  Camera,
  Dumbbell,
  Weight,
  BicepsFlexed,
  Trophy,
  // ── Rooms: outdoor & garden ──
  Trees,
  TreePine,
  TreeDeciduous,
  Fence,
  Flower2,
  Sprout,
  Leaf,
  Palmtree,
  RockingChair,
  Tent,
  Waves,
  Car,
  Warehouse,
  LampWallUp,
  Blinds,
  // ── Rooms: special purpose ──
  Baby,
  Dog,
  Cat,
  PawPrint,
  Rabbit,
  Bird,
  Fish,
  Turtle,
  Wine,
  BottleWine,
  Grape,
  Barrel,
  Beer,
  Martini,
  CupSoda,
  GlassWater,
  Coffee,
  Wrench,
  Hammer,
  Toolbox,
  CircuitBoard,
  Server,
  Heater,
  FireExtinguisher,
  Cctv,
  Church,
  Cross,
  Castle,
  Beaker,
  // ── Modes: time of day ──
  Sunrise,
  Sun,
  SunMedium,
  Sunset,
  Moon,
  MoonStar,
  CloudMoon,
  AlarmClock,
  EyeClosed,
  // ── Modes: activities & states ──
  PartyPopper,
  Brain,
  HeartPulse,
  BrushCleaning,
  Eye,
  // ── Modes: away & security ──
  Plane,
  Luggage,
  Shield,
  Lock,
  Users,
  HouseHeart,
  HouseWifi,
  // ── Modes: seasonal ──
  Snowflake,
  CloudLightning,
  Clover,
  CandyCane,
  // ── Nature & decorative ──
  Heart,
  Star,
  Home,
  Flame,
  Rainbow,
  Mountain,
  Shell,
  Anchor,
  Sailboat,
  Compass,
  Globe,
  Rocket,
  Binoculars,
  Flag,
  MapPin,
  Signpost,
  SolarPanel,
  Fan,
  LampCeiling,
  LampFloor,
  Hourglass,
  VenetianMask,
  Amphora,
  Award,
  Kayak,
  Bike,
  Bone,
  // ── Food ──
  Apple,
  Cookie,
  Cake,
  Pizza,
  Sandwich,
  Salad,
  Egg,
  Cherry,
  Banana,
  Wheat,
  Croissant,
  Lollipop,
  IceCream,
  // ── Devices / tech (used by TypeBadge, not shown in picker) ──
  Lightbulb,
  Plug,
  Radar,
  ScanEye,
  Speaker,
  Thermometer,
  ToggleLeft,
  SunDim,
  WandSparkles,
  Volume2,
  Power,
  Lamp,
  // ── UI / settings (used internally, not shown in picker) ──
  SlidersHorizontal,
  Headphones,
  CalendarClock,
  TrainFront,
  CloudSun,
  HardDrive,
  Sparkles,
  LayoutGrid,
  BarChart3,
  ScrollText,
  Settings,
  Clock,
  Activity,
  Zap,
  Battery,
  Droplets,
  Wind,
  Gem,
  Crown,
} from 'lucide-react'
import type { FC } from 'react'

/** Map of icon name (kebab-case) → Lucide component */
const ICON_MAP: Record<string, FC<LucideProps>> = {
  // Rooms: core living
  bed: Bed,
  'bed-double': BedDouble,
  'bed-single': BedSingle,
  sofa: Sofa,
  armchair: Armchair,
  tv: Tv,
  'tv-minimal': TvMinimal,
  'cooking-pot': CookingPot,
  'utensils-crossed': UtensilsCrossed,
  'fork-knife': ForkKnife,
  'chef-hat': ChefHat,
  refrigerator: Refrigerator,
  microwave: Microwave,
  bath: Bath,
  'shower-head': ShowerHead,
  toilet: Toilet,
  'towel-rack': TowelRack,
  'soap-dispenser-droplet': SoapDispenserDroplet,
  'mirror-round': MirrorRound,
  // Rooms: circulation & utility
  'door-open': DoorOpen,
  'door-closed': DoorClosed,
  footprints: Footprints,
  'washing-machine': WashingMachine,
  shirt: Shirt,
  'spray-can': SprayCan,
  archive: Archive,
  box: Box,
  key: Key,
  backpack: Backpack,
  'air-vent': AirVent,
  // Rooms: work & study
  briefcase: Briefcase,
  monitor: Monitor,
  laptop: Laptop,
  'book-open': BookOpen,
  library: Library,
  'lamp-desk': LampDesk,
  printer: Printer,
  'pen-tool': PenTool,
  // Rooms: hobbies & entertainment
  'gamepad-2': Gamepad2,
  puzzle: Puzzle,
  dices: Dices,
  blocks: Blocks,
  palette: Palette,
  paintbrush: Paintbrush,
  scissors: Scissors,
  spool: Spool,
  ruler: Ruler,
  'pencil-ruler': PencilRuler,
  piano: Piano,
  guitar: Guitar,
  drum: Drum,
  music: Music,
  mic: Mic,
  'audio-lines': AudioLines,
  clapperboard: Clapperboard,
  film: Film,
  projector: Projector,
  popcorn: Popcorn,
  camera: Camera,
  dumbbell: Dumbbell,
  weight: Weight,
  'biceps-flexed': BicepsFlexed,
  trophy: Trophy,
  // Rooms: outdoor & garden
  trees: Trees,
  'tree-pine': TreePine,
  'tree-deciduous': TreeDeciduous,
  fence: Fence,
  'flower-2': Flower2,
  sprout: Sprout,
  leaf: Leaf,
  palmtree: Palmtree,
  'rocking-chair': RockingChair,
  tent: Tent,
  waves: Waves,
  car: Car,
  warehouse: Warehouse,
  'lamp-wall-up': LampWallUp,
  blinds: Blinds,
  // Rooms: special purpose
  baby: Baby,
  dog: Dog,
  cat: Cat,
  'paw-print': PawPrint,
  rabbit: Rabbit,
  bird: Bird,
  fish: Fish,
  turtle: Turtle,
  wine: Wine,
  'bottle-wine': BottleWine,
  grape: Grape,
  barrel: Barrel,
  beer: Beer,
  martini: Martini,
  'cup-soda': CupSoda,
  'glass-water': GlassWater,
  coffee: Coffee,
  wrench: Wrench,
  hammer: Hammer,
  toolbox: Toolbox,
  'circuit-board': CircuitBoard,
  server: Server,
  heater: Heater,
  'fire-extinguisher': FireExtinguisher,
  cctv: Cctv,
  church: Church,
  cross: Cross,
  castle: Castle,
  beaker: Beaker,
  // Modes: time of day
  sunrise: Sunrise,
  sun: Sun,
  'sun-medium': SunMedium,
  sunset: Sunset,
  moon: Moon,
  'moon-star': MoonStar,
  'cloud-moon': CloudMoon,
  'alarm-clock': AlarmClock,
  'eye-closed': EyeClosed,
  // Modes: activities & states
  'party-popper': PartyPopper,
  brain: Brain,
  'heart-pulse': HeartPulse,
  'brush-cleaning': BrushCleaning,
  eye: Eye,
  // Modes: away & security
  plane: Plane,
  luggage: Luggage,
  shield: Shield,
  lock: Lock,
  users: Users,
  'house-heart': HouseHeart,
  'house-wifi': HouseWifi,
  // Modes: seasonal
  snowflake: Snowflake,
  'cloud-lightning': CloudLightning,
  clover: Clover,
  'candy-cane': CandyCane,
  // Nature & decorative
  heart: Heart,
  star: Star,
  home: Home,
  flame: Flame,
  rainbow: Rainbow,
  mountain: Mountain,
  shell: Shell,
  anchor: Anchor,
  sailboat: Sailboat,
  compass: Compass,
  globe: Globe,
  rocket: Rocket,
  binoculars: Binoculars,
  flag: Flag,
  'map-pin': MapPin,
  signpost: Signpost,
  'solar-panel': SolarPanel,
  fan: Fan,
  'lamp-ceiling': LampCeiling,
  'lamp-floor': LampFloor,
  hourglass: Hourglass,
  'venetian-mask': VenetianMask,
  amphora: Amphora,
  award: Award,
  kayak: Kayak,
  bike: Bike,
  bone: Bone,
  // Food
  apple: Apple,
  cookie: Cookie,
  cake: Cake,
  pizza: Pizza,
  sandwich: Sandwich,
  salad: Salad,
  egg: Egg,
  cherry: Cherry,
  banana: Banana,
  wheat: Wheat,
  croissant: Croissant,
  lollipop: Lollipop,
  'ice-cream': IceCream,
  // Devices / tech (used by TypeBadge, not in picker)
  lightbulb: Lightbulb,
  plug: Plug,
  radar: Radar,
  'scan-eye': ScanEye,
  speaker: Speaker,
  thermometer: Thermometer,
  'toggle-left': ToggleLeft,
  'sun-dim': SunDim,
  'wand-sparkles': WandSparkles,
  volume2: Volume2,
  power: Power,
  lamp: Lamp,
  // UI / settings (used internally, not in picker)
  'sliders-horizontal': SlidersHorizontal,
  headphones: Headphones,
  'calendar-clock': CalendarClock,
  'train-front': TrainFront,
  'cloud-sun': CloudSun,
  'hard-drive': HardDrive,
  sparkles: Sparkles,
  'layout-grid': LayoutGrid,
  'bar-chart-3': BarChart3,
  'scroll-text': ScrollText,
  settings: Settings,
  clock: Clock,
  activity: Activity,
  zap: Zap,
  battery: Battery,
  droplets: Droplets,
  wind: Wind,
  gem: Gem,
  crown: Crown,
}

export interface LucideIconProps extends Omit<LucideProps, 'name'> {
  /** Lucide icon name in kebab-case (e.g. "moon-star", "door-open") */
  name: string | null | undefined
}

/**
 * Renders a Lucide icon by name string. Returns null if name is missing or not in the curated set.
 */
export function LucideIcon({ name, ...props }: LucideIconProps) {
  if (!name) return null
  const IconComponent = ICON_MAP[name]
  if (!IconComponent) return null
  return <IconComponent {...props} />
}

/** All available icon entries grouped by category, for use in the IconPicker */
export const ICON_CATEGORIES: { label: string; icons: { name: string; keywords: string[] }[] }[] = [
  {
    label: 'Living spaces',
    icons: [
      { name: 'bed', keywords: ['bedroom', 'sleep', 'guest'] },
      { name: 'bed-double', keywords: ['bedroom', 'master', 'guest', 'double'] },
      { name: 'bed-single', keywords: ['bedroom', 'kids', 'spare', 'bunk', 'single'] },
      { name: 'sofa', keywords: ['living', 'lounge', 'couch', 'family', 'den'] },
      { name: 'armchair', keywords: ['chair', 'sitting', 'lounge', 'reading', 'snug'] },
      { name: 'tv', keywords: ['television', 'media', 'entertainment', 'rec'] },
      { name: 'tv-minimal', keywords: ['television', 'cinema', 'screen', 'media'] },
      { name: 'lamp-ceiling', keywords: ['room', 'ceiling', 'light', 'general'] },
      { name: 'lamp-floor', keywords: ['lounge', 'reading', 'standing', 'light'] },
      { name: 'lamp-desk', keywords: ['desk', 'study', 'office', 'reading', 'light'] },
      { name: 'lamp-wall-up', keywords: ['porch', 'exterior', 'wall', 'sconce'] },
      { name: 'rocking-chair', keywords: ['porch', 'veranda', 'balcony', 'sunroom', 'nursery'] },
      { name: 'blinds', keywords: ['window', 'shade', 'curtain'] },
    ],
  },
  {
    label: 'Kitchen and dining',
    icons: [
      { name: 'cooking-pot', keywords: ['kitchen', 'cook', 'stove'] },
      { name: 'utensils-crossed', keywords: ['kitchen', 'dining', 'food', 'eat'] },
      { name: 'fork-knife', keywords: ['dining', 'dinner', 'eat', 'restaurant', 'breakfast'] },
      { name: 'chef-hat', keywords: ['kitchen', 'chef', 'cook', 'bake'] },
      { name: 'refrigerator', keywords: ['kitchen', 'fridge', 'cold'] },
      { name: 'microwave', keywords: ['kitchen', 'heat', 'cook'] },
      { name: 'coffee', keywords: ['kitchen', 'morning', 'cafe', 'breakfast', 'nook'] },
      { name: 'wine', keywords: ['cellar', 'bar', 'dining'] },
      { name: 'bottle-wine', keywords: ['cellar', 'bar', 'wine'] },
      { name: 'grape', keywords: ['cellar', 'vineyard', 'wine'] },
      { name: 'barrel', keywords: ['cellar', 'brew', 'basement', 'storage'] },
      { name: 'beer', keywords: ['bar', 'pub', 'brew', 'tap'] },
      { name: 'martini', keywords: ['bar', 'cocktail', 'lounge', 'entertainment'] },
      { name: 'cup-soda', keywords: ['drinks', 'refreshment'] },
      { name: 'glass-water', keywords: ['water', 'drink', 'hydration'] },
    ],
  },
  {
    label: 'Bathroom and utility',
    icons: [
      { name: 'bath', keywords: ['bathroom', 'tub', 'bathtub', 'wash'] },
      { name: 'shower-head', keywords: ['bathroom', 'shower', 'ensuite', 'wet room'] },
      { name: 'toilet', keywords: ['loo', 'wc', 'powder room', 'cloakroom', 'restroom', 'lavatory'] },
      { name: 'towel-rack', keywords: ['bathroom', 'linen', 'towel'] },
      { name: 'soap-dispenser-droplet', keywords: ['bathroom', 'wash', 'soap', 'hygiene'] },
      { name: 'mirror-round', keywords: ['vanity', 'dressing', 'ensuite', 'makeup'] },
      { name: 'washing-machine', keywords: ['laundry', 'utility', 'wash'] },
      { name: 'shirt', keywords: ['wardrobe', 'closet', 'dressing', 'coat', 'clothes'] },
      { name: 'spray-can', keywords: ['cleaning', 'cupboard', 'utility', 'supplies'] },
      { name: 'heater', keywords: ['boiler', 'sauna', 'hot water', 'airing'] },
    ],
  },
  {
    label: 'Hallways and storage',
    icons: [
      { name: 'door-open', keywords: ['entrance', 'hallway', 'foyer', 'vestibule', 'lobby'] },
      { name: 'door-closed', keywords: ['closet', 'cupboard', 'storage', 'pantry'] },
      { name: 'footprints', keywords: ['hallway', 'corridor', 'landing', 'staircase', 'passage'] },
      { name: 'key', keywords: ['porch', 'entry', 'front door', 'key cupboard'] },
      { name: 'backpack', keywords: ['mudroom', 'boot room', 'school', 'drop zone'] },
      { name: 'archive', keywords: ['storage', 'attic', 'loft', 'filing'] },
      { name: 'box', keywords: ['storage', 'box room', 'junk room', 'spare'] },
      { name: 'air-vent', keywords: ['hvac', 'mechanical', 'ventilation', 'duct'] },
    ],
  },
  {
    label: 'Work and study',
    icons: [
      { name: 'briefcase', keywords: ['office', 'work', 'home office'] },
      { name: 'monitor', keywords: ['office', 'computer', 'desktop', 'screen'] },
      { name: 'laptop', keywords: ['study', 'work', 'portable', 'desk'] },
      { name: 'book-open', keywords: ['study', 'reading', 'library'] },
      { name: 'library', keywords: ['library', 'books', 'reading room', 'shelves'] },
      { name: 'printer', keywords: ['office', 'print', 'copy'] },
      { name: 'pen-tool', keywords: ['design', 'art', 'studio', 'creative'] },
      { name: 'brain', keywords: ['focus', 'study', 'thinking', 'deep work'] },
    ],
  },
  {
    label: 'Hobbies and craft',
    icons: [
      { name: 'palette', keywords: ['art', 'paint', 'creative', 'studio'] },
      { name: 'paintbrush', keywords: ['art', 'paint', 'studio', 'canvas'] },
      { name: 'scissors', keywords: ['sewing', 'craft', 'cut', 'tailor'] },
      { name: 'spool', keywords: ['sewing', 'thread', 'textile', 'craft', 'needle'] },
      { name: 'ruler', keywords: ['craft', 'measure', 'workshop', 'drafting'] },
      { name: 'pencil-ruler', keywords: ['drafting', 'design', 'architecture', 'craft'] },
      { name: 'camera', keywords: ['photography', 'darkroom', 'studio'] },
      { name: 'beaker', keywords: ['lab', 'science', 'brewing', 'experiment'] },
      { name: 'amphora', keywords: ['pottery', 'ceramics', 'classical', 'art'] },
      { name: 'venetian-mask', keywords: ['theatre', 'drama', 'costume', 'dress up'] },
    ],
  },
  {
    label: 'Music and entertainment',
    icons: [
      { name: 'piano', keywords: ['music', 'keyboard', 'piano room'] },
      { name: 'guitar', keywords: ['music', 'strings', 'practice'] },
      { name: 'drum', keywords: ['music', 'percussion', 'practice'] },
      { name: 'music', keywords: ['music', 'song', 'listening', 'audio'] },
      { name: 'mic', keywords: ['recording', 'podcast', 'studio', 'singing'] },
      { name: 'audio-lines', keywords: ['recording', 'sound', 'studio', 'mixing'] },
      { name: 'headphones', keywords: ['music', 'audio', 'listening', 'quiet'] },
      { name: 'clapperboard', keywords: ['cinema', 'movie', 'film', 'screening'] },
      { name: 'film', keywords: ['cinema', 'movie', 'screening', 'theatre'] },
      { name: 'projector', keywords: ['cinema', 'movie', 'screening', 'presentation'] },
      { name: 'popcorn', keywords: ['cinema', 'movie night', 'snack'] },
      { name: 'gamepad-2', keywords: ['game', 'play', 'gaming', 'console'] },
      { name: 'puzzle', keywords: ['playroom', 'kids', 'game', 'jigsaw'] },
      { name: 'dices', keywords: ['board game', 'game room', 'game night'] },
      { name: 'blocks', keywords: ['playroom', 'kids', 'toys', 'lego'] },
    ],
  },
  {
    label: 'Fitness and sport',
    icons: [
      { name: 'dumbbell', keywords: ['gym', 'exercise', 'fitness', 'weights'] },
      { name: 'weight', keywords: ['gym', 'weights', 'strength'] },
      { name: 'biceps-flexed', keywords: ['gym', 'muscle', 'strong', 'fitness'] },
      { name: 'heart-pulse', keywords: ['exercise', 'cardio', 'wellness', 'health'] },
      { name: 'bike', keywords: ['cycling', 'exercise', 'garage'] },
      { name: 'kayak', keywords: ['water sport', 'paddle', 'adventure'] },
      { name: 'trophy', keywords: ['trophy room', 'display', 'achievement'] },
      { name: 'award', keywords: ['achievement', 'medal', 'display'] },
    ],
  },
  {
    label: 'Outdoor and garden',
    icons: [
      { name: 'trees', keywords: ['garden', 'yard', 'back garden', 'woodland'] },
      { name: 'tree-pine', keywords: ['garden', 'evergreen', 'forest', 'christmas'] },
      { name: 'tree-deciduous', keywords: ['garden', 'orchard', 'shade'] },
      { name: 'fence', keywords: ['patio', 'deck', 'garden', 'fenced'] },
      { name: 'flower-2', keywords: ['garden', 'flower bed', 'conservatory', 'spring'] },
      { name: 'sprout', keywords: ['greenhouse', 'growing', 'seedlings', 'plant'] },
      { name: 'leaf', keywords: ['garden', 'eco', 'nature', 'autumn'] },
      { name: 'palmtree', keywords: ['sunroom', 'conservatory', 'balcony', 'terrace', 'tropical'] },
      { name: 'tent', keywords: ['outdoor', 'camping', 'garden cabin'] },
      { name: 'waves', keywords: ['pool', 'hot tub', 'water feature', 'pond'] },
      { name: 'car', keywords: ['garage', 'driveway', 'carport'] },
      { name: 'warehouse', keywords: ['garage', 'barn', 'shed', 'large'] },
      { name: 'solar-panel', keywords: ['solar', 'eco', 'roof', 'sustainable'] },
    ],
  },
  {
    label: 'Pets and animals',
    icons: [
      { name: 'dog', keywords: ['pet', 'puppy', 'kennel'] },
      { name: 'cat', keywords: ['pet', 'kitten'] },
      { name: 'paw-print', keywords: ['pet', 'animal', 'pet room'] },
      { name: 'rabbit', keywords: ['pet', 'bunny', 'hutch'] },
      { name: 'bird', keywords: ['aviary', 'pet', 'parrot', 'budgie'] },
      { name: 'fish', keywords: ['aquarium', 'tank', 'pond', 'pet'] },
      { name: 'turtle', keywords: ['reptile', 'pet', 'terrarium'] },
      { name: 'bone', keywords: ['dog room', 'pet', 'treats'] },
    ],
  },
  {
    label: 'Workshop and technical',
    icons: [
      { name: 'wrench', keywords: ['workshop', 'tools', 'repair', 'maintenance'] },
      { name: 'hammer', keywords: ['workshop', 'build', 'construction'] },
      { name: 'toolbox', keywords: ['workshop', 'tools', 'shed'] },
      { name: 'circuit-board', keywords: ['server room', 'tech', 'lab', 'electronics'] },
      { name: 'server', keywords: ['server room', 'network', 'data'] },
      { name: 'cctv', keywords: ['security', 'camera', 'monitoring'] },
      { name: 'fire-extinguisher', keywords: ['safety', 'fire', 'emergency'] },
    ],
  },
  {
    label: 'Special rooms',
    icons: [
      { name: 'baby', keywords: ['nursery', 'child', 'infant', 'crib'] },
      { name: 'church', keywords: ['prayer', 'chapel', 'meditation', 'worship'] },
      { name: 'cross', keywords: ['prayer', 'faith', 'spiritual'] },
      { name: 'castle', keywords: ['play castle', 'themed', 'kids', 'fantasy'] },
    ],
  },
  {
    label: 'Time of day',
    icons: [
      { name: 'sunrise', keywords: ['morning', 'dawn', 'early', 'wake'] },
      { name: 'sun', keywords: ['day', 'afternoon', 'bright', 'midday'] },
      { name: 'sun-medium', keywords: ['late morning', 'midday', 'noon'] },
      { name: 'sunset', keywords: ['evening', 'dusk', 'golden hour'] },
      { name: 'moon', keywords: ['night', 'dark', 'bedtime'] },
      { name: 'moon-star', keywords: ['late evening', 'night', 'stargazing'] },
      { name: 'cloud-moon', keywords: ['late night', 'overcast', 'cloudy'] },
      { name: 'alarm-clock', keywords: ['wake up', 'timer', 'morning'] },
      { name: 'eye-closed', keywords: ['sleep', 'rest', 'nap', 'bedtime'] },
      { name: 'coffee', keywords: ['morning', 'wake', 'breakfast'] },
      { name: 'eye', keywords: ['awake', 'alert', 'active', 'watch'] },
    ],
  },
  {
    label: 'Activities and moods',
    icons: [
      { name: 'party-popper', keywords: ['party', 'celebration', 'festive'] },
      { name: 'clapperboard', keywords: ['movie night', 'cinema'] },
      { name: 'popcorn', keywords: ['movie night', 'snack'] },
      { name: 'book-open', keywords: ['reading', 'quiet'] },
      { name: 'dumbbell', keywords: ['exercise', 'workout'] },
      { name: 'heart-pulse', keywords: ['exercise', 'wellness'] },
      { name: 'brain', keywords: ['focus', 'deep work', 'study'] },
      { name: 'briefcase', keywords: ['work mode', 'office'] },
      { name: 'cooking-pot', keywords: ['cooking', 'dinner'] },
      { name: 'brush-cleaning', keywords: ['cleaning', 'tidy'] },
      { name: 'heart', keywords: ['romantic', 'date night', 'love'] },
      { name: 'music', keywords: ['listening', 'relaxing'] },
      { name: 'house-heart', keywords: ['home', 'cozy', 'comfort'] },
      { name: 'house-wifi', keywords: ['smart home', 'connected'] },
    ],
  },
  {
    label: 'Away and security',
    icons: [
      { name: 'plane', keywords: ['away', 'vacation', 'travel', 'holiday'] },
      { name: 'luggage', keywords: ['vacation', 'travel', 'trip', 'away'] },
      { name: 'shield', keywords: ['guard', 'secure', 'protect', 'guest'] },
      { name: 'lock', keywords: ['lockdown', 'secure', 'night'] },
      { name: 'users', keywords: ['guest', 'entertaining', 'visitors'] },
    ],
  },
  {
    label: 'Seasonal and weather',
    icons: [
      { name: 'snowflake', keywords: ['winter', 'cold', 'christmas'] },
      { name: 'flower-2', keywords: ['spring', 'bloom'] },
      { name: 'leaf', keywords: ['autumn', 'fall'] },
      { name: 'cloud-lightning', keywords: ['storm', 'thunder', 'emergency'] },
      { name: 'clover', keywords: ['lucky', 'irish', 'seasonal'] },
      { name: 'candy-cane', keywords: ['christmas', 'holiday', 'festive'] },
      { name: 'rainbow', keywords: ['weather', 'colourful', 'pride'] },
      { name: 'flame', keywords: ['warm', 'cozy', 'fireplace', 'winter'] },
    ],
  },
  {
    label: 'Nature and places',
    icons: [
      { name: 'home', keywords: ['house', 'main', 'general'] },
      { name: 'mountain', keywords: ['landscape', 'scenic', 'outdoor'] },
      { name: 'shell', keywords: ['beach', 'coastal', 'sea'] },
      { name: 'anchor', keywords: ['nautical', 'dock', 'marine', 'harbour'] },
      { name: 'sailboat', keywords: ['nautical', 'lake', 'sailing', 'water'] },
      { name: 'compass', keywords: ['adventure', 'explore', 'navigate'] },
      { name: 'globe', keywords: ['world', 'earth', 'international'] },
      { name: 'binoculars', keywords: ['observation', 'lookout', 'view'] },
      { name: 'flag', keywords: ['landmark', 'marker', 'signal'] },
      { name: 'map-pin', keywords: ['location', 'spot', 'place'] },
      { name: 'signpost', keywords: ['direction', 'guidance', 'way'] },
    ],
  },
  {
    label: 'Food and treats',
    icons: [
      { name: 'apple', keywords: ['fruit', 'healthy', 'kitchen'] },
      { name: 'cherry', keywords: ['fruit', 'kitchen', 'sweet'] },
      { name: 'banana', keywords: ['fruit', 'kitchen', 'snack'] },
      { name: 'wheat', keywords: ['pantry', 'baking', 'grain', 'bread'] },
      { name: 'croissant', keywords: ['breakfast', 'bakery', 'pastry'] },
      { name: 'cookie', keywords: ['pantry', 'baking', 'treats', 'snack'] },
      { name: 'cake', keywords: ['celebration', 'birthday', 'party', 'baking'] },
      { name: 'pizza', keywords: ['takeaway', 'dinner', 'kitchen', 'food'] },
      { name: 'sandwich', keywords: ['lunch', 'kitchen', 'snack'] },
      { name: 'salad', keywords: ['healthy', 'kitchen', 'food'] },
      { name: 'egg', keywords: ['kitchen', 'breakfast', 'baking'] },
      { name: 'lollipop', keywords: ['sweets', 'kids', 'candy', 'treats'] },
      { name: 'ice-cream', keywords: ['summer', 'treats', 'dessert'] },
    ],
  },
  {
    label: 'General',
    icons: [
      { name: 'star', keywords: ['favourite', 'special', 'important'] },
      { name: 'heart', keywords: ['love', 'favourite', 'special'] },
      { name: 'gem', keywords: ['precious', 'special', 'diamond'] },
      { name: 'crown', keywords: ['royal', 'king', 'queen', 'master'] },
      { name: 'wand-sparkles', keywords: ['magic', 'fairy', 'fantasy'] },
      { name: 'sparkles', keywords: ['magic', 'special', 'fairy'] },
      { name: 'rocket', keywords: ['fun', 'launch', 'space', 'kids'] },
      { name: 'fan', keywords: ['cooling', 'ventilation', 'breeze'] },
      { name: 'hourglass', keywords: ['timed', 'transition', 'waiting'] },
    ],
  },
]

/** Flat list of all icon names in the curated set */
export const ALL_ICON_NAMES = ICON_CATEGORIES.flatMap(c => c.icons.map(i => i.name))

/** Check if an icon name is in the curated set */
export function isValidIconName(name: string): boolean {
  return name in ICON_MAP
}
