import { type LucideProps } from 'lucide-react'
import {
  // Rooms
  Bed,
  Sofa,
  CookingPot,
  Bath,
  DoorOpen,
  Lamp,
  Armchair,
  Tv,
  Baby,
  Warehouse,
  Trees,
  Car,
  WashingMachine,
  Shirt,
  Briefcase,
  BookOpen,
  Dumbbell,
  Gamepad2,
  Dog,
  UtensilsCrossed,
  Refrigerator,
  ShowerHead,
  Fence,
  Footprints,
  // Modes / time
  Sunrise,
  Sun,
  Sunset,
  Moon,
  MoonStar,
  CloudMoon,
  Coffee,
  AlarmClock,
  Eye,
  PartyPopper,
  Plane,
  Shield,
  // Nature / decorative
  Heart,
  Star,
  Home,
  Flower2,
  Leaf,
  Flame,
  Snowflake,
  Rainbow,
  Palette,
  Mountain,
  Shell,
  Fish,
  Bird,
  Cat,
  // Devices / tech
  Lightbulb,
  Plug,
  Radar,
  ScanEye,
  Speaker,
  Thermometer,
  ToggleLeft,
  SunDim,
  DoorClosed,
  WandSparkles,
  Volume2,
  Power,
  // UI / settings
  SlidersHorizontal,
  Headphones,
  CalendarClock,
  TrainFront,
  CloudSun,
  HardDrive,
  Sparkles,
  LayoutGrid,
  BarChart3,
  ScrollText,
  Settings,
  Music,
  Clock,
  Activity,
  Zap,
  Battery,
  Droplets,
  Wind,
  // General
  Gem,
  Crown,
  Rocket,
  Compass,
  Anchor,
  Globe,
  Tent,
  TreePine,
} from 'lucide-react'
import type { FC } from 'react'

/** Map of icon name (kebab-case) → Lucide component */
const ICON_MAP: Record<string, FC<LucideProps>> = {
  // Rooms
  bed: Bed,
  sofa: Sofa,
  'cooking-pot': CookingPot,
  bath: Bath,
  'door-open': DoorOpen,
  lamp: Lamp,
  armchair: Armchair,
  tv: Tv,
  baby: Baby,
  warehouse: Warehouse,
  trees: Trees,
  car: Car,
  'washing-machine': WashingMachine,
  shirt: Shirt,
  briefcase: Briefcase,
  'book-open': BookOpen,
  dumbbell: Dumbbell,
  'gamepad-2': Gamepad2,
  dog: Dog,
  'utensils-crossed': UtensilsCrossed,
  refrigerator: Refrigerator,
  'shower-head': ShowerHead,
  fence: Fence,
  footprints: Footprints,
  // Modes / time
  sunrise: Sunrise,
  sun: Sun,
  sunset: Sunset,
  moon: Moon,
  'moon-star': MoonStar,
  'cloud-moon': CloudMoon,
  coffee: Coffee,
  'alarm-clock': AlarmClock,
  eye: Eye,
  'party-popper': PartyPopper,
  plane: Plane,
  shield: Shield,
  // Nature / decorative
  heart: Heart,
  star: Star,
  home: Home,
  'flower-2': Flower2,
  leaf: Leaf,
  flame: Flame,
  snowflake: Snowflake,
  rainbow: Rainbow,
  palette: Palette,
  mountain: Mountain,
  shell: Shell,
  fish: Fish,
  bird: Bird,
  cat: Cat,
  // Devices / tech
  lightbulb: Lightbulb,
  plug: Plug,
  radar: Radar,
  'scan-eye': ScanEye,
  speaker: Speaker,
  thermometer: Thermometer,
  'toggle-left': ToggleLeft,
  'sun-dim': SunDim,
  'door-closed': DoorClosed,
  'wand-sparkles': WandSparkles,
  volume2: Volume2,
  power: Power,
  // UI / settings
  'sliders-horizontal': SlidersHorizontal,
  headphones: Headphones,
  'calendar-clock': CalendarClock,
  'train-front': TrainFront,
  'cloud-sun': CloudSun,
  'hard-drive': HardDrive,
  sparkles: Sparkles,
  'layout-grid': LayoutGrid,
  'bar-chart-3': BarChart3,
  'scroll-text': ScrollText,
  settings: Settings,
  music: Music,
  clock: Clock,
  activity: Activity,
  zap: Zap,
  battery: Battery,
  droplets: Droplets,
  wind: Wind,
  // General
  gem: Gem,
  crown: Crown,
  rocket: Rocket,
  compass: Compass,
  anchor: Anchor,
  globe: Globe,
  tent: Tent,
  'tree-pine': TreePine,
}

export interface LucideIconProps extends Omit<LucideProps, 'name'> {
  /** Lucide icon name in kebab-case (e.g. "moon-star", "door-open") */
  name: string | null | undefined
}

/**
 * Renders a Lucide icon by name string. Returns null if name is missing or not in the curated set.
 */
export function LucideIcon({ name, ...props }: LucideIconProps) {
  if (!name) return null
  const IconComponent = ICON_MAP[name]
  if (!IconComponent) return null
  return <IconComponent {...props} />
}

/** All available icon entries grouped by category, for use in the IconPicker */
export const ICON_CATEGORIES: { label: string; icons: { name: string; keywords: string[] }[] }[] = [
  {
    label: 'Rooms',
    icons: [
      { name: 'bed', keywords: ['bedroom', 'sleep'] },
      { name: 'sofa', keywords: ['living', 'lounge', 'couch'] },
      { name: 'cooking-pot', keywords: ['kitchen', 'cook'] },
      { name: 'utensils-crossed', keywords: ['kitchen', 'dining', 'food'] },
      { name: 'refrigerator', keywords: ['kitchen', 'fridge'] },
      { name: 'bath', keywords: ['bathroom', 'wash'] },
      { name: 'shower-head', keywords: ['bathroom', 'shower'] },
      { name: 'door-open', keywords: ['room', 'entrance', 'hall'] },
      { name: 'lamp', keywords: ['light', 'reading', 'desk'] },
      { name: 'armchair', keywords: ['chair', 'sitting', 'lounge'] },
      { name: 'tv', keywords: ['television', 'media', 'entertainment'] },
      { name: 'baby', keywords: ['nursery', 'child', 'kids'] },
      { name: 'warehouse', keywords: ['garage', 'storage', 'shed'] },
      { name: 'trees', keywords: ['garden', 'outdoor', 'yard'] },
      { name: 'fence', keywords: ['garden', 'patio', 'outdoor'] },
      { name: 'car', keywords: ['garage', 'drive', 'parking'] },
      { name: 'washing-machine', keywords: ['laundry', 'utility'] },
      { name: 'shirt', keywords: ['wardrobe', 'closet', 'dressing'] },
      { name: 'briefcase', keywords: ['office', 'work', 'study'] },
      { name: 'book-open', keywords: ['library', 'study', 'reading'] },
      { name: 'dumbbell', keywords: ['gym', 'exercise', 'fitness'] },
      { name: 'gamepad-2', keywords: ['game', 'play', 'entertainment'] },
      { name: 'dog', keywords: ['pet', 'animal'] },
      { name: 'footprints', keywords: ['hallway', 'corridor', 'landing'] },
    ],
  },
  {
    label: 'Time and modes',
    icons: [
      { name: 'sunrise', keywords: ['morning', 'dawn', 'early'] },
      { name: 'sun', keywords: ['day', 'afternoon', 'bright'] },
      { name: 'sunset', keywords: ['evening', 'dusk'] },
      { name: 'moon', keywords: ['night', 'dark', 'sleep'] },
      { name: 'moon-star', keywords: ['night', 'late', 'evening'] },
      { name: 'cloud-moon', keywords: ['night', 'cloudy', 'late'] },
      { name: 'coffee', keywords: ['morning', 'wake', 'breakfast'] },
      { name: 'alarm-clock', keywords: ['wake', 'timer', 'morning'] },
      { name: 'eye', keywords: ['awake', 'watch', 'alert'] },
      { name: 'party-popper', keywords: ['celebration', 'festive', 'fun'] },
      { name: 'plane', keywords: ['away', 'travel', 'vacation'] },
      { name: 'shield', keywords: ['guard', 'secure', 'protect', 'guest'] },
    ],
  },
  {
    label: 'Nature',
    icons: [
      { name: 'heart', keywords: ['love', 'favourite'] },
      { name: 'star', keywords: ['favourite', 'special'] },
      { name: 'home', keywords: ['house', 'main'] },
      { name: 'flower-2', keywords: ['garden', 'plant', 'spring'] },
      { name: 'leaf', keywords: ['nature', 'plant', 'eco'] },
      { name: 'flame', keywords: ['fire', 'warm', 'cozy'] },
      { name: 'snowflake', keywords: ['cold', 'winter', 'freeze'] },
      { name: 'rainbow', keywords: ['colour', 'weather'] },
      { name: 'palette', keywords: ['colour', 'art', 'creative'] },
      { name: 'mountain', keywords: ['outdoor', 'landscape'] },
      { name: 'shell', keywords: ['beach', 'ocean', 'sea'] },
      { name: 'fish', keywords: ['aquarium', 'water', 'pet'] },
      { name: 'bird', keywords: ['outdoor', 'nature', 'pet'] },
      { name: 'cat', keywords: ['pet', 'animal'] },
      { name: 'tree-pine', keywords: ['forest', 'outdoor', 'christmas'] },
      { name: 'tent', keywords: ['outdoor', 'camping'] },
    ],
  },
  {
    label: 'Things',
    icons: [
      { name: 'lightbulb', keywords: ['light', 'idea', 'lamp'] },
      { name: 'plug', keywords: ['power', 'socket', 'electrical'] },
      { name: 'speaker', keywords: ['music', 'sound', 'audio'] },
      { name: 'headphones', keywords: ['music', 'audio', 'listen'] },
      { name: 'music', keywords: ['song', 'audio', 'sound'] },
      { name: 'gem', keywords: ['precious', 'diamond', 'special'] },
      { name: 'crown', keywords: ['royal', 'king', 'queen'] },
      { name: 'rocket', keywords: ['launch', 'fast', 'space'] },
      { name: 'compass', keywords: ['direction', 'explore', 'navigate'] },
      { name: 'anchor', keywords: ['nautical', 'dock', 'marine'] },
      { name: 'globe', keywords: ['world', 'earth', 'international'] },
      { name: 'wand-sparkles', keywords: ['magic', 'fairy', 'fantasy'] },
      { name: 'sparkles', keywords: ['scene', 'magic', 'special'] },
    ],
  },
]

/** Flat list of all icon names in the curated set */
export const ALL_ICON_NAMES = ICON_CATEGORIES.flatMap(c => c.icons.map(i => i.name))

/** Check if an icon name is in the curated set */
export function isValidIconName(name: string): boolean {
  return name in ICON_MAP
}
